[build]
builder = "nixpacks"

[deploy]
preDeployCommand = "python manage.py migrate --no-input"
startCommand = "gunicorn gestion_productos.wsgi --bind 0.0.0.0:$PORT --log-file -"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
