[build]
builder = "nixpacks"

[deploy]
preDeployCommand = "python manage.py migrate --no-input && python manage.py collectstatic --no-input"
startCommand = "bash start.sh"
healthcheckPath = "/"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
